services:
  bot:
    container_name: bot
    image: python
    command: sh -c "pip install --no-cache-dir git+https://github.com/Rapptz/discord.py@master && git clone https://github.com/ceilingtilefan/forwardrepostbot && cd forwardrepostbot && python bot.py"
    restart: unless-stopped